### PR TITLE
Movie Night

### PR DESCRIPTION
**Pull request by discountrainbows**
We should watch more movies

### CODE REVIEW

**Comment by discountrainbows** [comment]
@bob You should check this out.

**Comment by discountrainbows** [comment]
hey @stephenbunch What do you think about watching Rogue One instead?

**Comment by discountrainbows** [comment]
@bob Hey, I made your change.

**Comment by discountrainbows** [comment]
@stephenbunch sign off

**Comment by bob** [comment]
@discountrainbows Hey, check the Github markup

**Pull request merged**
